const DUMMY_ANYBRAIN_DLL = new Uint8Array(
  atob(
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAwAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5v" +
    "dCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAADxXQ7dtTxgjrU8YI61PGCO" +
    "271lj7Q8YI7bvWCPtDxgjtu9Yo+0PGCOUmljaLU8YI4AAAAAAAAAAAAAAAAAAAAA" +
    "UEUAAGSGAgAiXTVmAAAAAAAAAADwACIgCwIOJgACAAAAAgAAAAAAABAQAAAAEAAA" +
    "AAAAgAEAAAAAEAAAAAIAAAYAAAAAAAAABgAAAAAAAAAAMAAAAAQAAAAAAAACAGAB" +
    "AAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAACAgAADkAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAcAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALnRleHQAAAAWAAAAABAAAAACAAAABAAA" +
    "AAAAAAAAAAAAAAAAIAAAYC5yZGF0YQAAjAEAAAAgAAAAAgAAAAYAAAAAAAAAAAAA" +
    "AAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAADPAw8zMzMzMzMzMzMzMzMy4AQAAAMMAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAACJdNWYAAAAADQAAAGgAAAAkIQAAJAcAAAAAAAAAAAAA/////wAAAACEIAAA" +
    "AQAAAAYAAAAGAAAASCAAAGAgAAB4IAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAA" +
    "lyAAAKggAAC6IAAA0SAAAOMgAAD0IAAAAAABAAIAAwAEAAUAZHVtbXlfYW55YnJh" +
    "aW4uZGxsAEFueWJyYWluUGF1c2VTREsAQW55YnJhaW5SZXN1bWVTREsAQW55YnJh" +
    "aW5TZXRDcmVkZW50aWFscwBBbnlicmFpblNldFVzZXJJZABBbnlicmFpblN0YXJ0" +
    "U0RLAEFueWJyYWluU3RvcFNESwAYAAAAAoACgAAAAAAAAAAAHCEAAAgAAAAAEAAA" +
    "FgAAAAAAAAAAEAAAFgAAAC50ZXh0JG1uAAAAAAAgAAAgAAAALnJkYXRhAAAgIAAA" +
    "5AAAAC5lZGF0YQAABCEAACAAAAAucmRhdGEkdm9sdG1kAAAAJCEAAGgAAAAucmRh" +
    "dGEkenp6ZGJnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
  )
  .split("")
  .map(c => c.charCodeAt(0))
);

const DUMMY_ANYBRAIN_DLL_CRC32 = (CRC32.buf(DUMMY_ANYBRAIN_DLL) >>> 0);
