const DUMMY_WAGON_SOUND_DLL = new Uint8Array(
  atob(
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAwAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5v" +
    "dCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAADxXQ7dtTxgjrU8YI61PGCO" +
    "271lj7Q8YI7bvWCPtDxgjtu9Yo+0PGCOUmljaLU8YI4AAAAAAAAAAAAAAAAAAAAA" +
    "UEUAAGSGAgD1czBmAAAAAAAAAADwACIgCwIOJgACAAAAAgAAAAAAABAQAAAAEAAA" +
    "AAAAgAEAAAAAEAAAAAIAAAYAAAAAAAAABgAAAAAAAAAAMAAAAAQAAAAAAAACAGAB" +
    "AAAQAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAACAgAACsAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAcAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALnRleHQAAAAWAAAAABAAAAACAAAABAAA" +
    "AAAAAAAAAAAAAAAAIAAAYC5yZGF0YQAAVAEAAAAgAAAAAgAAAAYAAAAAAAAAAAAA" +
    "AAAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAADPAw8zMzMzMzMzMzMzMzMy4AQAAAMMAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAPVzMGYAAAAADQAAAGgAAADsIAAA7AYAAAAAAAAAAAAA/////wAAAABwIAAA" +
    "AQAAAAQAAAAEAAAASCAAAFggAABoIAAAABAAAAAQAAAAEAAAABAAAIAgAACXIAAA" +
    "qSAAALogAAAAAAEAAgADAHdhZ29uX3NvdW5kLmRsbABBbnlicmFpblNldENyZWRl" +
    "bnRpYWxzAEFueWJyYWluU2V0VXNlcklkAEFueWJyYWluU3RhcnRTREsAQW55YnJh" +
    "aW5TdG9wU0RLAAAAGAAAAAKAAoAAAAAAAAAAAOQgAAAIAAAAABAAABYAAAAAAAAA" +
    "ABAAABYAAAAudGV4dCRtbgAAAAAAIAAAIAAAAC5yZGF0YQAAICAAAKwAAAAuZWRh" +
    "dGEAAMwgAAAgAAAALnJkYXRhJHZvbHRtZAAAAOwgAABoAAAALnJkYXRhJHp6emRi" +
    "ZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
  )
  .split("")
  .map(c => c.charCodeAt(0))
);

const DUMMY_WAGON_SOUND_DLL_CRC32 = (CRC32.buf(DUMMY_WAGON_SOUND_DLL) >>> 0);
